#############################################################################
# Makefile for building: ParrotShare.app/Contents/MacOS/ParrotShare
# Generated by qmake (2.01a) (Qt 4.5.1) on: Mon Nov 16 20:30:03 2009
# Project:  ParrotShare.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile ParrotShare.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.5/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtNetwork.framework/Versions/4/Headers -I/usr/include/QtNetwork -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/Library/Frameworks/QtXml.framework/Versions/4/Headers -I/usr/include/QtXml -I/usr/include -I. -I. -I../../Software/include -I/opt/local/include -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtXml -framework QtGui -framework Carbon -framework AppKit -framework QtNetwork -framework SystemConfiguration -framework QtCore -lz -lm -framework ApplicationServices
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.3

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		parrotshare.cpp \
		parrotconfiguration.cpp \
		datafriend.cpp \
		datashare.cpp \
		permission.cpp \
		friendlistmodel.cpp moc_parrotshare.cpp
OBJECTS       = main.o \
		parrotshare.o \
		parrotconfiguration.o \
		datafriend.o \
		datashare.o \
		permission.o \
		friendlistmodel.o \
		moc_parrotshare.o
DIST          = /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		ParrotShare.pro
QMAKE_TARGET  = ParrotShare
DESTDIR       = 
TARGET        = ParrotShare.app/Contents/MacOS/ParrotShare

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile ParrotShare.app/Contents/PkgInfo ParrotShare.app/Contents/Resources/empty.lproj ParrotShare.app/Contents/Info.plist $(TARGET)

$(TARGET): ui_parrotshare.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ParrotShare.app/Contents/MacOS/ || $(MKDIR) ParrotShare.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ParrotShare.pro  /usr/local/Qt4.5/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.5/mkspecs/common/unix.conf \
		/usr/local/Qt4.5/mkspecs/common/mac.conf \
		/usr/local/Qt4.5/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.5/mkspecs/qconfig.pri \
		/usr/local/Qt4.5/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.5/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.5/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.5/mkspecs/features/debug.prf \
		/usr/local/Qt4.5/mkspecs/features/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.5/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.5/mkspecs/features/qt.prf \
		/usr/local/Qt4.5/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.5/mkspecs/features/moc.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.5/mkspecs/features/resources.prf \
		/usr/local/Qt4.5/mkspecs/features/uic.prf \
		/usr/local/Qt4.5/mkspecs/features/yacc.prf \
		/usr/local/Qt4.5/mkspecs/features/lex.prf \
		/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtXml.framework/QtXml.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile ParrotShare.pro
/usr/local/Qt4.5/mkspecs/common/unix.conf:
/usr/local/Qt4.5/mkspecs/common/mac.conf:
/usr/local/Qt4.5/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.5/mkspecs/qconfig.pri:
/usr/local/Qt4.5/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.5/mkspecs/features/qt_config.prf:
/usr/local/Qt4.5/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.5/mkspecs/features/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.5/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.5/mkspecs/features/debug.prf:
/usr/local/Qt4.5/mkspecs/features/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.5/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.5/mkspecs/features/warn_on.prf:
/usr/local/Qt4.5/mkspecs/features/qt.prf:
/usr/local/Qt4.5/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.5/mkspecs/features/moc.prf:
/usr/local/Qt4.5/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.5/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.5/mkspecs/features/resources.prf:
/usr/local/Qt4.5/mkspecs/features/uic.prf:
/usr/local/Qt4.5/mkspecs/features/yacc.prf:
/usr/local/Qt4.5/mkspecs/features/lex.prf:
/usr/local/Qt4.5/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtXml.framework/QtXml.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.5/mkspecs/macx-g++ -macx -o Makefile ParrotShare.pro

ParrotShare.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) ParrotShare.app/Contents || $(MKDIR) ParrotShare.app/Contents 
	@$(DEL_FILE) ParrotShare.app/Contents/PkgInfo
	@echo "APPL????" >ParrotShare.app/Contents/PkgInfo
ParrotShare.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) ParrotShare.app/Contents/Resources || $(MKDIR) ParrotShare.app/Contents/Resources 
	@touch ParrotShare.app/Contents/Resources/empty.lproj
	
ParrotShare.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) ParrotShare.app/Contents || $(MKDIR) ParrotShare.app/Contents 
	@$(DEL_FILE) ParrotShare.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ParrotShare,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.5/mkspecs/macx-g++/Info.plist.app >ParrotShare.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/ParrotShare1.0.0 || $(MKDIR) .tmp/ParrotShare1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ParrotShare1.0.0/ && $(COPY_FILE) --parents parrotshare.h parrotconfiguration.h datafriend.h datashare.h permission.h friendlistmodel.h .tmp/ParrotShare1.0.0/ && $(COPY_FILE) --parents main.cpp parrotshare.cpp parrotconfiguration.cpp datafriend.cpp datashare.cpp permission.cpp friendlistmodel.cpp .tmp/ParrotShare1.0.0/ && $(COPY_FILE) --parents parrotshare.ui .tmp/ParrotShare1.0.0/ && (cd `dirname .tmp/ParrotShare1.0.0` && $(TAR) ParrotShare1.0.0.tar ParrotShare1.0.0 && $(COMPRESS) ParrotShare1.0.0.tar) && $(MOVE) `dirname .tmp/ParrotShare1.0.0`/ParrotShare1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ParrotShare1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r ParrotShare.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_parrotshare.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_parrotshare.cpp
moc_parrotshare.cpp: parrotconfiguration.h \
		datashare.h \
		permission.h \
		datafriend.h \
		friendlistmodel.h \
		parrotshare.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ parrotshare.h -o moc_parrotshare.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all: ui_parrotshare.h
compiler_uic_clean:
	-$(DEL_FILE) ui_parrotshare.h
ui_parrotshare.h: parrotshare.ui
	/Developer/Tools/Qt/uic parrotshare.ui -o ui_parrotshare.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp parrotshare.h \
		parrotconfiguration.h \
		datashare.h \
		permission.h \
		datafriend.h \
		friendlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

parrotshare.o: parrotshare.cpp parrotshare.h \
		parrotconfiguration.h \
		datashare.h \
		permission.h \
		datafriend.h \
		friendlistmodel.h \
		ui_parrotshare.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parrotshare.o parrotshare.cpp

parrotconfiguration.o: parrotconfiguration.cpp parrotconfiguration.h \
		datashare.h \
		permission.h \
		datafriend.h \
		friendlistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parrotconfiguration.o parrotconfiguration.cpp

datafriend.o: datafriend.cpp datafriend.h \
		permission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datafriend.o datafriend.cpp

datashare.o: datashare.cpp datashare.h \
		permission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datashare.o datashare.cpp

permission.o: permission.cpp permission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o permission.o permission.cpp

friendlistmodel.o: friendlistmodel.cpp friendlistmodel.h \
		datafriend.h \
		permission.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o friendlistmodel.o friendlistmodel.cpp

moc_parrotshare.o: moc_parrotshare.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parrotshare.o moc_parrotshare.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

